name: The Kinney Family
favicon: null
layout_spectrum: 0
typography_spectrum: 0.49529
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e141c'
    - '#f9fcfe'
    - '#b4b9bf'
    - '#8f543e'
    - '#56c430'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
